#!/usr/bin/env python
import sys, parser, compiler, symbol, token, pprint

#src = open(sys.argv[1]).read()
#print src

st = parser.suite('print 7*3+4').tolist()

print st
print '-----------'

def foo(st):
    if type(st) == type([]):
        if st[0] in symbol.sym_name:
            st[0] = '%s' % symbol.sym_name[st[0]]
        elif st[0] in token.tok_name:
            st[0] = '%s' % token.tok_name[st[0]]
        for x in st[1:]:
            foo(x)

foo(st)

print '-----------'

pp = pprint.PrettyPrinter()#indent=4)
pp.pprint(st)

#ast = parser.sequence2ast(st)

#code = parser.compileast(ast)

#exec(code)
